server_properties:
    ip_address:  "127.0.0.1"
    port:        "8080"
    server_name: "exec-processor"
    endpoint:    "/api/v1/remote-execution"
    server_crt:  "server.crt"
    server_key:  "server.key"
    